function [NN]= lstm_nn(n_features, X_train, X_test, y_train, y_test, network) 
    % Debug
    disp(" => Network: " + network);

    % Train Neural Network
    layers = [
        sequenceInputLayer(n_features)
        lstmLayer(100, 'OutputMode', 'last')
        fullyConnectedLayer(3)
        softmaxLayer
        classificationLayer
    ];
    
    options = trainingOptions(...
            'adam', ...
            'InitialLearnRate', 0.01, ...
            'GradientThreshold',1, ...
            'MaxEpochs', 1, ...
            'MiniBatchSize', 27, ...
            'SequenceLength', 'longest', ...
            'Shuffle', 'never', ...
            'ValidationData', {X_test, y_test}, ...
            'ValidationFrequency', 30, ...
            'Plots','training-progress' ...
            );
    NN = trainNetwork(X_train, y_train, layers, options);
end