function [NN]= lstm(X_train, X_test, y_train, y_test) 
    % Debug
    disp(" => Network: " + network);

    % Train Neural Network
    layers = [
        sequenceInputLayer(29)
        lstm(100, 'OutputMode', 'last');
        fullyConnectedLayer(3)
        softmaxLayer
        classificationLayer
    ];
    
    options = trainingOptions(...
            'adam', ...
            'InitialLearnRate', 0.01, ...
            'GradientThreshold',1, ...
            'MaxEpochs', 100, ...
            'MiniBatchSize', 27, ...
            'SequenceLength', 'longest', ...
            'Shuffle', 'never', ...
            'ValidationData', {X_test, y_test}, ...
            'ValidationFrequency', 30, ...
            'Plots','trainingprogress' ...
            );
    NN = trainNetwork(X_train, y_train, layers, options);
end